name: Build Plugin Zip

on:
  workflow_dispatch:

env:
  PLUGIN_NAME: MrpixWeRePack

jobs:
  run:
    name: Build and Validate Zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.PLUGIN_NAME }}

      - name: Install shopware-cli
        uses: FriendsOfShopware/shopware-cli-action@v1

      - name: Build
        run: shopware-cli extension zip ${{ env.PLUGIN_NAME }} --git-commit "${{ github.sha }}"

      - name: Rename
        run: mv ${{ env.PLUGIN_NAME }}-${{ github.sha }}.zip ${{ env.PLUGIN_NAME }}.zip

      - name: Validate
        run: shopware-cli extension validate ${{ env.PLUGIN_NAME }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_NAME }}
          path: ${{ env.PLUGIN_NAME }}.zip
          if-no-files-found: error
          retention-days: 90