name: "Build & Release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  PLUGIN_NAME: MrpixWeRePack

jobs:
  build:
    name: Build and Validate Zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.PLUGIN_NAME }}

      - name: Install shopware-cli
        uses: FriendsOfShopware/shopware-cli-action@v1

      - name: Build
        run: shopware-cli extension zip ${{ env.PLUGIN_NAME }} --git-commit "${{ github.sha }}"

      - name: Rename
        run: mv MrpixWeRepack-${{ github.sha }}.zip ${{ env.PLUGIN_NAME }}.zip

      - name: Validate
        run: shopware-cli extension validate ${{ env.PLUGIN_NAME }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_NAME }}
          path: ${{ env.PLUGIN_NAME }}.zip
          if-no-files-found: error
          retention-days: 5

  release:
    name: "Release"
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: "Determine release version"
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: "Download plugin zip"
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PLUGIN_NAME }}
          path: build

      - name: "Append release version to plugin zip"
        run: mv build/${{ env.PLUGIN_NAME }}.zip build/${{ env.PLUGIN_NAME }}-${{ env.VERSION }}.zip

      - name: "Create plugin release"
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*